### ISSUE TITLE
lag in data processing, stuck on October 2023?

### ISSUE THREAD

**Issue by shallot** [mnzpk/WikiNav#12]
Hi there,

It looks like WikiNav hasn't been updated with the November or December clickstream data. I hope this is the right forum to report production issues :)

There was a lag in getting the November data, cf. https://meta.wikimedia.org/wiki/Research_talk:Wikipedia_clickstream#update_frequency? but it seems to be resolved now

Can someone check into this?

Thanks,
Josip

**Comment by martingerlach** [comment]
Thanks for reaching out.
There was a lag with the publication of the Nobember data, so the WikiNav tool didnt get the updated data (it checks on the 12th of each month if a new snapshot is available). With publication of the December data on Jan 3rd, the WikiNav tool got updated as expected on Jan 12.
