### ISSUE TITLE
Sources & destinations API returning 404

### ISSUE THREAD

**Issue by tylerb1** [mnzpk/WikiNav#14]
Hi there. Thanks again for this awesome project!

Currently, requests like `https://wikinav.wmcloud.org/api/v1/en/Chocolate/sources/2023-11` or `https://wikinav.wmcloud.org/api/v1/en/Chocolate/destinations/2023-11` are failing with a 404. If any maintainers have time, could they look into this?

If you recommend a particular way of reproducing and hosting the dumps that provide this data, I could try setting that up myself. Some background: I have a side project that uses Wikinav as an API to display "neighborhoods" of articles in 3D and would love to keep it going (https://github.com/tylerb1/wikjumps).

**Comment by martingerlach** [comment]
@tylerb1 thanks for flagging this.
this is an artifact from the issue with updating the november snapshot #12 
@mnzpk manually ran the script to import those snapshots. it should now work as expected. thanks @mnzpk 
if you want to host the data yourself in a similar way, you can see how we import the [clickstream dumps](https://dumps.wikimedia.org/other/clickstream/readme.html) here: https://github.com/mnzpk/WikiNav/tree/main/server/api

Best,
Martin
