### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by olea** [mnzpk/WikiNav#8]
Hi:

Could be possible to run WikiNav in a local container? Or is it coupled with Toolforge?

Thanks in advance.

**Comment by martingerlach** [comment]
Hi,
to be honest, not sure.
You can find more information on the technical infrastructure of the tool in this blogpost: https://techblog.wikimedia.org/2021/09/17/analyzing-the-wikipedia-clickstream-just-got-easier-with-wikinav/
I hope this helps. 

Feel free to re-open the issue if you have follow-up questions
